spring:
  application:
    name: crm-api
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/FREEPDB1
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true