spring:
  application:
    name: crm-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@//localhost:1522/FREEPDB1}
    username: ${SPRING_DATASOURCE_USERNAME:system}
    password: ${SPRING_DATASOURCE_PASSWORD:oracle}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:oracle.jdbc.OracleDriver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

minio:
  url: ${MINIO_URL:http://127.0.0.1:9000}
  bucket:
    name: ${MINIO_BUCKET_NAME:crmbucket}
  access:
    key: ${MINIO_ROOT_USER:minioadmin}
    secret: ${MINIO_ROOT_PASSWORD:minioadmin}