spring:
  application:
    name: crm-api
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/FREEPDB1
    #url: jdbc:oracle:thin:@//localhost:1522/FREEPDB1
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
minio:
  url: http://127.0.0.1
  #url: http://minio:9000
  port: 9000
  bucket:
    name: crmbucket
  access:
     key: minioadmin
     secret: minioadmin